// TODO: Create a function to generate markdown for README
function generateMarkdown(answers) {
  return `
  # ${answers.title} :metal:

  ![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)) <br />

  ## Description  :clipboard:
  ${answers.description}

  ## Table of Contents
  -[Description](#description)
  -[Installation](#installation)
  -[Usage](#usage)
  -[Lincense](#lincense)
  -[Contributing](#contributing)
  -[Tests](#tests)
  -[Questions](#questions)

  ## Installation :floppy_disk:
  ${answers.installation}

  ## Usage :warning:
  ${answers.usage}

  ## License :scroll:
  ![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)
  <br />
  This application is uses the ${answers.license} license. 

  ## Contributors :family:
  ${answers.contributing}

  ## Tests 🧪
  ${answers.tests}

  ## Questions :question:
  ### For any issues please reach out to ${answers.questions}
  <br />
  Feel free to reach out to me at <a href="mailto:${answers.email}?"><img src="https://img.shields.io/badge/gmail-%23DD0031.svg?&style=for-the-badge&logo=gmail&logoColor=white"/></a> with any questions :wave: 
  <br />
  Check out the rest of my Github: https://github.com/${answers.username} :octocat: 


  _This README was generated by [README-GEN](https://github.com/peter-izzo/README-GEN) :godmode:_

`;
}

module.exports = generateMarkdown;
